name: combi
description: A simple parser combinator library for Dart.
version: 0.0.1
repository: https://github.com/mkalmousli/combi.dart

environment:
  sdk: ^3.9.2

dependencies:


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  path: ^1.9.0
